# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Timo Bertram
email:
description: >- # this means to ignore newlines until "baseurl:"
 Personal website of Timo Bertram
url: "https://timobertram.github.io"
twitter_username: BertramTimo
github_username: timobertram
minimal_mistakes_skin: mint
repository: "timobertram/timobertram.github.io"
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: CET # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Timo Bertram"
  avatar : "/assets/images/IDBild.jpg"
  bio    : "PhD Student Artificial Intelligence in Games @ Johannes Kepler University Linz"
  links:
    - label: "Mail"
      icon: "fa fa-solid fa-envelope"
      url: "mailto:tbertram@faw.jku.at"
    - label: "Linz"
      icon: "fa fa-compass"
      url: "https://www.google.com/maps/place/Johannes+Kepler+Universit%C3%A4t+Linz+-+JKU/@48.336614,14.3171163,17z/data=!3m1!4b1!4m5!3m4!1s0x477398434ec8e84d:0xe0d1670c08989881!8m2!3d48.336614!4d14.319305"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BertramTimo"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=b8aWdXcAAAAJ&hl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timobertram"

footer:
  links:
    - label: "Mail"
      icon: "fa fa-solid fa-envelope"
      url: "mailto:tbertram@faw.jku.at"
    - label: "Linz"
      icon: "fa fa-compass"
      url: "https://www.google.com/maps/place/Johannes+Kepler+Universit%C3%A4t+Linz+-+JKU/@48.336614,14.3171163,17z/data=!3m1!4b1!4m5!3m4!1s0x477398434ec8e84d:0xe0d1670c08989881!8m2!3d48.336614!4d14.319305"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BertramTimo"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=b8aWdXcAAAAJ&hl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timobertram"

atom_feed:
  hide: true

defaults:
  # _postss
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
